#! /usr/bin/env python

import sys
from random import sample

if len(sys.argv) < 2:
    print('USAGE: RandomSampling list.file sample.size')
    sys.exit(1)


def random_sampling(listfile, sampling_size):
    sampling_file = open(listfile).readlines()
    sampling_pool = []
    for i in sampling_file:
        sampling_pool.append(i.replace('\n', ''))
    if sampling_size > len(sampling_pool):
        print('Error: Sampling size should not be greater than the size of samples pool.')
    else:
        for i in sample(sampling_pool, sampling_size):
            print(i)


random_sampling(sys.argv[1], int(sys.argv[2]))
